### ISSUE TITLE
Add function to clear/empty hashmap without deallocating.

### ISSUE THREAD

**Issue by MarcusTL12** [tidwall/hashmap.c#1]
Very minor, optional issue. I generally like when data structures have some way to clear the contents. This way I don't need to allocate a whole new hashmap if I am done with the map and want a new similarly sized hashmap. It is easy to implement externally by deleting all the entries, but i feel it might be faster to have an internal implementation.

**Comment by tidwall** [comment]
I just added a `hashmap_clear` function. This clears the hash map, but it won't always avoid allocations because the map's might have grown larger than the capacity, and in order to be valid we must reallocate the bucket buffer to the correct size.

I added an `update_cap` option to the function which will change the map's capacity to match the current number of buckets and thus avoiding the allocation.
