### ISSUE TITLE
[Improvement request] Custom allocator per hashmap.

### ISSUE THREAD

**Issue by thetoster** [tidwall/hashmap.c#6]
It would be great to have possibility to set different allocator per instance of hashmap.

**Comment by tidwall** [comment]
I agree. Maybe something like `hashmap_new_with_allocator`. And then `hashmap_new` would continue to use the global allocator.

**Comment by thetoster** [comment]
I was more thinking about changing curent API, there is already function:
```void hashmap_set_allocator(void *(*malloc)(size_t), void (*free)(void*));```
If it follow this same pattern like others, adding just first param of type hashmap will be good enough for me :)
However if you intend to not break back compatibility then ```hashmap_new_with_allocator``` is a good point.

**Comment by tidwall** [comment]
Setting the allocator from `hashmap_set_allocator` after calling `hashmap_new` probably won't work because the target hashmap will have already been allocated using the standard library allocator.
Using a `hashmap_new_with_allocator` gives us the ability to allocate the new hashmap using the custom allocator from the start.

**Comment by thetoster** [comment]
You right, I was more thinking about allocator for items not whole structure (perspective of user), but when I looked inside I know what you mean. Your approach is much better.

**Comment by tidwall** [comment]
I added the `hashmap_new_with_allocator` and deprecated the `hashmap_set_allocator` function.
