### ISSUE TITLE
Segfault when calling hashmap_set

### ISSUE THREAD

**Issue by IndianBoy6** [tidwall/hashmap.c#8]
I'm using this library to make a 2D hashmap for a game I'm developing. For the "keys", I have 2 64 bit ints that represent the x and z coordinate. For the "values", I just have a huge array that represents the data in the x, z chunk. When I run hashmap_set, I get a segfault. I ran it with GDB and it says its coming from this line:
```c
211         char edata[map->bucketsz]; // VLA;
```
If I'm doing something wrong, does anyone have any ideas why? If it's something wrong with the library (which it is most likely not), is there some feature that needs to be implemented? Thanks.

**Comment by tidwall** [comment]
The error you are encountering may be due to the size of the `map->bucketsz` being too big to dynamically allocate a [VAL](https://en.wikipedia.org/wiki/Variable-length_array) on the stack. 

How large is the `elsize` (element size) param that you are sending to the `hashmap_new()` function? 

Generally you want to keep the element size as small as needed, where each element is an individual unit that is hashable and comparable. If you are intending on storing very large elements, then it may be best to use pointers as your elements, in which each is an individual allocation on the heap.

BTW, I recently replaced the VLA with an allocation in v0.3.1, which will generally avoid stack crashes for massive elements. If that is in fact your issue then it may be worthwhile to update.

**Comment by IndianBoy6** [comment]
When I initialize the world (that's the struct that contains the hashmap), the size is sizeof(chunk), which is the struct that contains the keys and values.

**Comment by IndianBoy6** [comment]
Just downloaded the new version and it's not segfaulting in the same place anymore. However, when I run hashmap_set, it still returns NULL. I'm sure this is a problem with my code, but I can't seem to figure out where. For the compare function, I'm just comparing a.x == b.x && a.y == b.y so I'm not sure why it isn't working.

**Comment by tidwall** [comment]
> the size is sizeof(chunk), which is the struct that contains the keys and values

How many keys and values is this? What is this as number of bytes?
This should be relatively small.

The `elsize` is meant to represent the size of a single element. Such as a one key/value pair. Each pair must be exactly the same elsize.

> For the compare function, I'm just comparing a.x == b.x && a.y == b.y so I'm not sure why it isn't working.

The return value of the compare function should -1, 0, or 1, where -1 is `a < b`, 0 is `a == b`, and 1 is `a > b`.

A `a.x == b.x && a.y == b.y` probably won't work.

So if you are using multiple values you need to do something like:

```
int compare(a, b) {
    if (a.x < b.x) {
        return -1;
    } else if (a.x > b.x) {
        return 1;
    } else if (a.y < b.y) {
        return -1;
    } else if (a.y > b.y) {
        return 1;
    } else {
        return 0;
    }
}
```

**Comment by IndianBoy6** [comment]
Does it matter that it returns -1, 1 depending on whether it's more/less, or is it just "something else" than 0?

**Comment by IndianBoy6** [comment]
Sorry for wasting your time, turns out when I ran hashmap_get, I was just passing the key, not the chunk struct. I'm going to keep this open for a bit more because I might be doing something in an inefficient way with the compare function.

**Comment by tidwall** [comment]
I usually make my compare function return the correct value because I often reuse compare with other collections, such as b-tree and qsort. But because it's a hashmap, I guess it probably doesn't matter as long as equals == zero, and not-equals == not zero.

**Comment by IndianBoy6** [comment]
Okay, thanks!
